### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Lecrapouille** [MPETREMANN11/php#1]
1. In https://github.com/MPETREMANN11/php/blob/main/Forth.php#L21
`var $enable_keywords_links;` typo: shall be `var $enable_keyword_links;` without `s`
2. https://github.com/MPETREMANN11/php/blob/main/Forth.php#L68
`var $commentFlag;` shall not be explictely `var $commentFlag = FALSE;` instead ?
3. https://github.com/MPETREMANN11/php/blob/main/Forth.php#L138
`if (ord($word) == 92) {` shall be `if ((ord($word) == 92) and ($this->commentFlag = FALSE)) {` to avoid having several `<span>` for example `/ this is a comment with 1 / 3 which fails`
4. https://github.com/MPETREMANN11/php/blob/main/Forth.php#L60
`$this->keySource = array();` shall not be declared as var outside the function ?
5. The `<img src="images/forthHighlight.png"/>` in the README has broken link. You can simply write in pure markdown code:
`![alt forth](images/forthHighlight.png)`

**Comment by MPETREMANN11** [comment]
Corrected

**Comment by MPETREMANN11** [comment]
closed
